### ISSUE TITLE
Data i Access

### ISSUE THREAD

**Issue by rlindsberg** [rlindsberg/1351IV-Data-Storage-Paradigms#20]
A part of #16 

## Todos:
- [x] Implementera AN och FN
### Variationen är inte bra i vissa tabeller:
- [x] Inga två utställningar har samma titel eller samma startdatum.
- [x] Inga två produkter har samma typ
- [x] Ingen produkt har flera konstverk
